/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstablecimientoIdRouteImport } from './routes/establecimiento.$id'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstablecimientoIdRoute = EstablecimientoIdRouteImport.update({
  id: '/establecimiento/$id',
  path: '/establecimiento/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favoritos': typeof FavoritosRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/establecimiento/$id': typeof EstablecimientoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favoritos': typeof FavoritosRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/establecimiento/$id': typeof EstablecimientoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favoritos': typeof FavoritosRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/establecimiento/$id': typeof EstablecimientoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/favoritos'
    | '/mapa'
    | '/perfil'
    | '/establecimiento/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/favoritos'
    | '/mapa'
    | '/perfil'
    | '/establecimiento/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/favoritos'
    | '/mapa'
    | '/perfil'
    | '/establecimiento/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FavoritosRoute: typeof FavoritosRoute
  MapaRoute: typeof MapaRoute
  PerfilRoute: typeof PerfilRoute
  EstablecimientoIdRoute: typeof EstablecimientoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/establecimiento/$id': {
      id: '/establecimiento/$id'
      path: '/establecimiento/$id'
      fullPath: '/establecimiento/$id'
      preLoaderRoute: typeof EstablecimientoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FavoritosRoute: FavoritosRoute,
  MapaRoute: MapaRoute,
  PerfilRoute: PerfilRoute,
  EstablecimientoIdRoute: EstablecimientoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
